### ISSUE TITLE
Informations

### ISSUE THREAD

**Issue by LuigiElleBalotta** [Shauren/tc-client-launcher#2]
Is it needed to start TC-master at current revision? In affermative case, please update http://www.trinitycore.info
Screenshots of the client in the Readme.md?
Does this auto-patches wow.exe if there is not one already patched in WoW Folder?

Thank you

**Comment by Aokromes** [comment]
you see this under trinitycore organization?

**Comment by Shauren** [comment]
> Is it needed to start TC-master at current revision? In affermative case, please update http://www.trinitycore.info

Yes, bnetserver must be running and no, http://www.trinitycore.info will not be updated as @Aokromes said, this project is not in TrinityCore organization

> Screenshots of the client in the Readme.md?

On my TODO list, it will be announced somewhere on the forum

> Does this auto-patches wow.exe if there is not one already patched in WoW Folder?

No. (this might change for windows in 7.3)

**Comment by LuigiElleBalotta** [comment]
> you see this under trinitycore organization?


It's a tool for TC and some1 could write a thread in the forum to publish after in confluence app.. No?

Thanks for the other answers

**Comment by kazeel11** [comment]
Description: I will do my best....
Having a problem with the client_launcher_32.exe**

Dragging client_launcher_32.exe to wow.exe starts the game, but will not use tc_bundle.txt to login.
It wow is dragged to client_launcher_32.exe
Creating patched binary...
EX: could not open C:\program Files\World of Warcraft\wow.exe\tc_bundle.txt

**Not sure**
current error from blizzard_console.lua
https://gist.github.com/kazeel11/9e2d2b2d5727c17ad412b215a4fdb754

If this is a crash, post the crashlog (upload to https://gist.github.com/).


7.3.2 25497

7.3.2

I am not sure what to post that might help to find the problem but I just build this server from https://github.com/TrinityCore/TrinityCore/tree/7.3.2
The build was prefect, never had a single error.
Did although had to add two db2 file to extract from client, I think ItemLevelSelectorQuality.db2 and ItemLevelSelectorQualitySet.db2

I would just like to know if I could add the tc_bundle.txt to the compiler for the client_launcher_32.exe

TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win32, Release, Static) (worldserver-daemon)

TDB_full_720.00_2017_04_18 with all updates from sql files.
Win 7




I am sorry to write this here but I tried to start a new issue but it would not let me submit it.

**Comment by Shauren** [comment]
@kazeel11 First, you are on the wrong project (this launcher is a GUI one with autologin support working only for 7.2.5)
Second, the new TrinityCore launcher changed a bit compared to old connection_patcher, you will need to drag "World of Warcraft" folder on client_launcher_32.exe (not wow.exe)
Finally, wow client will be crashing a lot on 7.3.2 branch which is why it hasn't been merged to master yet

**Comment by kazeel11** [comment]
Okay, Thank you for the help. One more quick question, does it still create a wow-patched.exe or just run the client and pray?

**Comment by Shauren** [comment]
just runs the client

**Comment by LuigiElleBalotta** [comment]
> you see this under trinitycore organization?

No, so don't reply :)
