### ISSUE TITLE
TCL001 When Trying to Point to Virtual Machine

### ISSUE THREAD

**Issue by StonedCookieGaming** [Shauren/tc-client-launcher#3]
My server is located on a virtual machine and for some reason I keep running into an error when trying to set the login URL. What exactly do I need to use to point to the bnetserver on my VM?

**Comment by Shauren** [comment]
https://[LoginREST.ExternalAddress or LoginREST.LocalAddress]:[LoginREST.Port]/bnetserver

where LoginREST. are entries from bnetserver.conf

**Comment by StonedCookieGaming** [comment]
It didn't work. The bnetserver is running and ports are open. I tried with and without brackets as well.

**Comment by Shauren** [comment]
Can you even log in without using this launcher? (with arctium only)

**Comment by StonedCookieGaming** [comment]
Yes I can. Others can as well.

**Comment by Shauren** [comment]
So `(irm -Uri VALUE_FROM_LOGIN_URL/login/ -SkipCertificateCheck -Method Get).inputs` works? (powershell)

It should look like this
![obraz](https://github.com/Shauren/tc-client-launcher/assets/297439/47d4c3f6-252b-4271-83e8-3a612bf9ef77)

**Comment by StonedCookieGaming** [comment]
It doesn't work in PowerShell no. We use the version of Arctium that doesn't flash the console.

**Comment by Shauren** [comment]
It doesnt matter which version of arctium launcher you have, its not used until you click "play" in my launcher but from what i see you arent there yet (yes, it relies on arctium to be present in wow dir too)

So how exactly do your LoginREST configs look like?

**Comment by StonedCookieGaming** [comment]
It's pointing to the right directory. Here's a screenshot of my end.
![Screenshot 2023-05-29 171902](https://github.com/Shauren/tc-client-launcher/assets/12970601/a2d2d1dc-ad3d-465c-b10b-30f4b7904218)

**Comment by Shauren** [comment]
It should not have /login/ in it

**Comment by StonedCookieGaming** [comment]
Okay I removed it. It doesn't seem to want to work still :(

**Comment by Shauren** [comment]
This will be a dumb question but are you by any chance using your external ip when bnetserver is running on the same network as your client? That obviously cannot work, you have to use a local address on that pc

**Comment by StonedCookieGaming** [comment]
Negative. The server is on a virtual machine.

**Comment by Shauren** [comment]
Is the virtual machine running inside your network or some random hosting service? I ask because I can connect to the ip you showed on your screenshot

![obraz](https://github.com/Shauren/tc-client-launcher/assets/297439/af44754b-1800-4875-b1a3-a72229ca4959)

**Comment by StonedCookieGaming** [comment]
It's a random hosting service. Am I using the wrong version of your launcher?

**Comment by StonedCookieGaming** [comment]
Do you happen to have a copy of your launcher? Compiling the source is proving to be rather difficult.

**Comment by StonedCookieGaming** [comment]
I got the launcher to get past the error but now when I enter my email and password and hit submit it crashes.

**Comment by Shauren** [comment]
Yes, it started crashing for me too, currently its unusable

**Comment by Shauren** [comment]
The crashing is now fixed and new release was published
