### ISSUE TITLE
Build fail on Mac M2

### ISSUE THREAD

**Issue by WebberLai** [Shauren/tc-client-launcher#5]
Hi I try to build your project but fail 
I'm not sure my progress is correct . could you check it ?

1. clone project
2. open terminal app , `cd ~/Document/tc-client-launcher`
3. enter `npm run build-all-dev`
4. shows log below 

> > tc-launcher@1.0.6 build-all-dev
> > npm run build && npm run build-electron && npm run build-native
> 
> 
> > tc-launcher@1.0.6 build
> > ng build
> 
> ✔ Browser application bundle generation complete.
> ✔ Copying assets complete.
> ✔ Index html generation complete.
> 
> Initial Chunk Files | Names         |  Raw Size | Estimated Transfer Size
> main.js             | main          | 350.70 kB |                87.84 kB
> polyfills.js        | polyfills     |  35.39 kB |                10.98 kB
> styles.css          | styles        |   2.31 kB |               610 bytes
> runtime.js          | runtime       |   1.06 kB |               596 bytes
> 
>                     | Initial Total | 389.47 kB |               100.00 kB
> 
> Build at: 2024-08-09T06:32:47.481Z - Hash: ea1d9b503e54ed8c - Time: 1491ms
> 
> Warning: /Users/developer/Documents/Git Project/tc-client-launcher/src/environments/environment.prod.ts is part of the TypeScript compilation but it's unused.
> Add only entry points to the 'files' or 'include' properties in your tsconfig.
> 
> Warning: /Users/developer/Documents/Git Project/tc-client-launcher/src/ipc/crypto-result.ts is part of the TypeScript compilation but it's unused.
> Add only entry points to the 'files' or 'include' properties in your tsconfig.
> 
> Warning: /Users/developer/Documents/Git Project/tc-client-launcher/src/ipc/log-event.ts is part of the TypeScript compilation but it's unused.
> Add only entry points to the 'files' or 'include' properties in your tsconfig.
> 
> 
> 
> > tc-launcher@1.0.6 build-electron
> > tsc -p src/desktop-app --outDir dist/ && cp src/desktop-app/package.json dist/
> 
> 
> > tc-launcher@1.0.6 build-native
> > electron-rebuild -f && cp build/Release/tc_launcher.node dist/
> 
> ⠹ Searching dependency treeAttempting to build a module with a space in the path
> See https://github.com/nodejs/node-gyp/issues/65#issuecomment-368820565 for reasons why this may not work
> ⠼ Building module: tc-client-launcher, Completed: 0(node:92148) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> Traceback (most recent call last):
>   File "/Users/developer/Documents/Git Project/tc-client-launcher/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
>     import gyp  # noqa: E402
>     ^^^^^^^^^^
>   File "/Users/developer/Documents/Git Project/tc-client-launcher/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
>     import gyp.input
>   File "/Users/developer/Documents/Git Project/tc-client-launcher/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
>     from distutils.version import StrictVersion
> ModuleNotFoundError: No module named 'distutils'
> Error: `gyp` failed with exit code: 1
>     at ChildProcess.onCpExit (/Users/developer/Documents/Git Project/tc-client-launcher/node_modules/node-gyp/lib/configure.js:325:16)
>     at ChildProcess.emit (node:events:520:28)
>     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
> 
> ✖ Rebuild Failed
> 
> An unhandled error occurred inside electron-rebuild
> node-gyp failed to rebuild '/Users/developer/Documents/Git Project/tc-client-launcher'
> 
> Error: node-gyp failed to rebuild '/Users/developer/Documents/Git Project/tc-client-launcher'
>     at ChildProcess.<anonymous> (/Users/developer/Documents/Git Project/tc-client-launcher/node_modules/@electron/rebuild/lib/module-type/node-gyp/node-gyp.js:118:24)
>     at ChildProcess.emit (node:events:520:28)
>     at ChildProcess._handle.onexit (node:internal/child_process:294:12)

**Comment by Shauren** [comment]
This will not work on mac - it uses arctium under the hood to do the client launching (the purpose of this launcher is to provide autologin functionality)

And since there is no arctium launcher for mac, this one doesn't work on mac either.
